### ISSUE TITLE
ARGOCD_SERVER doesn't honor fqdn

### ISSUE THREAD

**Issue by matoszz** [argoproj-labs/argocd-image-updater#107]
**Describe the bug**

When specifying the env var `ARGOCD_SERVER` either via configmap or in the deployment directly, it does not actually perform an fqdn lookup for the correct IP address and uses the internal cluster service IP instead.

e.x.:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-image-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-image-updater
    spec:
      containers:
      - command:
        - /usr/local/bin/argocd-image-updater
        - run
        env:
        - name: ARGOCD_GRPC_WEB
          value: "true"
        - name: ARGOCD_SERVER
          value: "https://argo.mydomain.com"
```
```
time="2020-10-08T21:41:37Z" level=error msg="error while communicating with ArgoCD" argocd_server="https://argo.mydomain.com" grpc_web=true grpc_webroot= insecure=false plaintext=false
time="2020-10-08T21:41:37Z" level=error msg="Error: rpc error: code = Unknown desc = Post \"https://https//argo.mydomain.com
ineering/application.ApplicationService/List\": dial tcp: lookup https on 100.64.0.10:53: no such host"
```

**To Reproduce**
Provide an https URL in the ARGOCD_SERVER env var either via configmap or in the deployment directly

**Expected behavior**

Would expect the fqdn lookup to return the ingress IP and not the cluster local IP. When attempting to use the cluster local service (e.g. leaving ARGOCD_SERVER empty) it then tries to use https to the local pod:

```
time="2020-10-08T21:47:56Z" level=error msg="error while communicating with ArgoCD" argocd_server=argocd-server.argocd grpc_web=true grp
c_webroot= insecure=true plaintext=false
time="2020-10-08T21:47:56Z" level=error msg="Error: rpc error: code = Unknown desc = Post \"https://argocd-server.argocd:443/application
.ApplicationService/List\": read tcp 192.168.3.70:53584->192.168.0.17:8080: read: connection reset by peer"
```
This is with `argocd-server` running with the `--insecure` flag because if you try and run it without this flag, the error is then that the certificate it's using isn't valid. 

Also, specifying INSECURE false vs. true in the argocd image updater seems to have no bearing on it's use of https:

```
time="2020-10-08T21:50:22Z" level=error msg="error while communicating with ArgoCD" argocd_server=argocd-server.argocd grpc_web=true grp
c_webroot= insecure=false plaintext=false
time="2020-10-08T21:50:22Z" level=error msg="Error: rpc error: code = Unknown desc = Post \"https://argocd-server.argocd:443/application
.ApplicationService/List\": read tcp 192.168.3.154:51664->192.168.1.64:8080: read: connection reset by peer"
```

**Version**
Argocd v1.7.6
Argocd image updater v.0.7.0

**Comment by matoszz** [comment]
Trying all permutations of options (INSECURE true vs. false, GRPC_WEB true vs. false) still yields unsuccessful connection attempts even when hitting the pod IP's directly: 

```
time="2020-10-08T21:53:01Z" level=error msg="error while communicating with ArgoCD" argocd_server=argocd-server.argocd grpc_web=false gr
pc_webroot= insecure=false plaintext=false
time="2020-10-08T21:53:01Z" level=error msg="Error: read tcp 192.168.3.122:55310->192.168.1.64:8080: read: connection reset by peer"
```

**Comment by jannfis** [comment]
Hi, please try if a non-URL value for `ARGOCD_SERVER`, i.e. `argo.mydomain.com` or `argo.mydomain.com:443` (without the protocol specified) works for you.

**Comment by matoszz** [comment]
ARGOCD_SERVER = `argo.mydomain.com` + ARGOCD_GRPC_WEB = `false` + ARGOCD_INSECURE = `true`
```
time="2020-10-12T01:44:03Z" level=error msg="Error: rpc error: code = Internal desc = transport: received the unexpected content-type \"
text/plain; charset=utf-8\""
```
ARGOCD_SERVER = `argo.mydomain.com` + ARGOCD_GRPC_WEB = `true` + ARGOCD_INSECURE = `true`
```
time="2020-10-12T01:55:11Z" level=error msg="Error: rpc error: code = Unauthenticated desc = no session information"
```
ARGOCD_SERVER = `argo.mydomain.com` + ARGOCD_GRPC_WEB = `false` + ARGOCD_INSECURE = `false`
```
time="2020-10-12T01:57:00Z" level=error msg="Error: rpc error: code = Internal desc = transport: received the unexpected content-type \"
text/plain; charset=utf-8\""
```
ARGOCD_SERVER = `argo.mydomain.com` + ARGOCD_GRPC_WEB = `true` + ARGOCD_INSECURE = `false`
```
time="2020-10-12T02:01:29Z" level=error msg="Error: rpc error: code = Unauthenticated desc = no session information"
```
ARGOCD_SERVER = `argo.mydomain.com:443` + ARGOCD_GRPC_WEB = `false` + ARGOCD_INSECURE = `true`
```
time="2020-10-12T01:46:13Z" level=error msg="Error: rpc error: code = Internal desc = transport: received the unexpected content-type \"
text/plain; charset=utf-8\""
```
ARGOCD_SERVER = `argo.mydomain.com:443` + ARGOCD_GRPC_WEB = `true` + ARGOCD_INSECURE = `false`
```
time="2020-10-12T01:48:39Z" level=error msg="Error: rpc error: code = Unauthenticated desc = no session information"
```
ARGOCD_SERVER = `argo.mydomain.com:443` + ARGOCD_GRPC_WEB = `false` + ARGOCD_INSECURE = `false`
```
time="2020-10-12T01:50:05Z" level=error msg="Error: rpc error: code = Internal desc = transport: received the unexpected content-type \"
text/plain; charset=utf-8\""
```
ARGOCD_SERVER = `argo.mydomain.com:443` + ARGOCD_GRPC_WEB = `true` + ARGOCD_INSECURE = `true`
```
time="2020-10-12T01:53:05Z" level=error msg="Error: rpc error: code = Unauthenticated desc = no session information"
```

**Comment by matoszz** [comment]
trying to rule out the ingress; disabling default backend, creating a dedicated gRPC ingress, results in: 

```
/application.ApplicationService/List failed with status code 502
```

**Comment by jannfis** [comment]
If you receive a message such as `Error: rpc error: code = Unauthenticated desc = no session information`, it means that the connection parameters actually were correct, but that authentication is required at the endpoint. Credentials can be supplied via `ARGOCD_TOKEN` environment variable.

**Comment by matoszz** [comment]
Interesting. I've created the secret per the instructions in the docs but now the secret is empty. I'm noticing that after I create it, restart the pods, it gets wiped out. Any inkling about why that would be occurring?

**Comment by matoszz** [comment]
Also, even when I generate the JWT token and put it into the env var of the deployment directly (instead of creating a secret with it) it still fails in the same way. Is there a step I'm missing w/r/t creating the user + JWT token?

**Comment by matoszz** [comment]
I finally found the permutation of settings that function 👏  - using _not_ the grpc ingress (the regular one) with GRPC_WEB as "true" and insecure as "false" seems to finally start logging out checks

**Comment by jannfis** [comment]
Closing this as I believe has been resolved.

Feel free to reopen if it is not.

**Comment by Manoj-07** [comment]
@matoszz sir I had enabled ingressGrpc to true value bur still getting the error. Could you please let me know how to resolve it?
ERROR:: application.ApplicationService/Create failed with status code 502
