### ISSUE TITLE
After successfully updating the image, the Helm values passed in the application are reset

### ISSUE THREAD

**Issue by MairaTariq16** [argoproj-labs/argocd-image-updater#692]
**Describe the bug**
After successfully updating the image, the Helm values passed in the application are reset.

**To Reproduce**

1. Create an Argo Application resource with Helm as source. Pass values in `valuesObject`. Annotate with `"argocd-image-updater.argoproj.io/image.update-strategy": "digest"` and other relevant annotations for image-updater.
2. Sync the application, resources are rendered successfully. 
3. Push a new image on same tag. Argocd-image-updater successfully detects the change but resets the values passed to Helm chart in Application spec. 

**Expected behavior**
The Helm values passed in the Application spec should remain unchanged after updating the image.

**Additional context**
I assume image-updater updates the resources by passing image.tag as parameter to helm, and dismisses the values set previously. I have tried to pass values as `parameters` in Application spec and it worked fine. Works with `values` passed too. But I want to resort back to using valuesObject to specify values for my Helm release. 

**Version**
ArgoCD: 2.10.2
Argocd-image-updater: 0.12.2

**Comment by llinros** [comment]
If the helm values are passed using `spec.source.helm.values: |`  block, those are also not removed like other parameters

The issue seems to be only affecting `spec.source.helm.valuesObject`, which gets removed when image-updater does updates to the Application

**Comment by Kiliandeca** [comment]
Hello, I was experiencing the same issue you described and found out the problem doesn't appear on the current master branch.

The latest ArgoCD Image Updater release `0.12.2` was done 1 year and 4 months ago in January 2023 but ArgoCD merged the `valuesObject` feature 6 months later in June 2023 https://github.com/argoproj/argo-cd/pull/11538 so that's why it wasn't supported in `0.12.2`.

It's hard to tell if there will be a new release soon so your best chance is to use the latest docker image tag `quay.io/argoprojlabs/argocd-image-updater:latest` for now.

**Comment by MairaTariq16** [comment]
Closing this issue as it was resolved in latest version (0.14.0).

**Comment by jjayabal23** [comment]
The issue still appears in v0.14.0.

I have a valuesObject like below,
`valuesObject:
  flowset:
    tag: '0'
  image:
    tag: '1.0.0'`

It works and updates the image.tag to the latest available version while the flowset.tag is '0'

But the same does not work when the flowset.tag is updated to '1' like below,
`valuesObject:
  flowset:
    tag: '1'
  image:
    tag: '1.0.0'`

Also, I notice that the image updater is adding the updated image.tag in to helm.parameters with `forceString` set to `true`. It would be good if the image updater updates the `valuesObject.image.tag`
