### ISSUE TITLE
Not working with registry parameter.

### ISSUE THREAD

**Issue by crazy-canux** [argoproj-labs/argocd-image-updater#974]
**Describe the bug**

when there are three parameters in helm value, it's not working.

   argocd-image-updater.argoproj.io/myalias.helm.image-name: backstage.image.repository
   argocd-image-updater.argoproj.io/myalias.helm.image-tag: backstage.image.tag

**To Reproduce**

```
    argocd-image-updater.argoproj.io/image-list: myalias=my-registry/my-repository:latest
    argocd-image-updater.argoproj.io/myalias.update-strategy: digest
    argocd-image-updater.argoproj.io/myalias.force-update: true
   argocd-image-updater.argoproj.io/myalias.helm.image-name: backstage.image.repository
   argocd-image-updater.argoproj.io/myalias.helm.image-tag: backstage.image.tag
```

in helm value:

```
    backstage:
        image:
            registry:
            repository:
            tag:
```

**Expected behavior**
update image in argocd.

**Additional context**
without image-name and image-tag annotation, will get another issue.
new image detected, but not updated in argocd.

`time="2024-12-18T09:57:48Z" level=info msg="Successfully updated image 'my-registry/my-repositor@dummy' to 'my-registry/my-repository@sha256:2defa431dcf22d2baf5d4b6d8241caf12d7ad4f09a9168f65327bd80af6e235f', but pending spec update (dry run=false)" alias=myalias application=test image_name=my-repository image_tag=dummy registry=my-registry`

**Version**
0.15.0

**Logs**

`Failed to pull image "my-registry/my-registry/my-repository:latest@sha256:292638896047d855da3c2f531ccecd0e172a06344840bebf5c2d7d59c36c2e08": rpc error: code = NotFound desc = failed to pull and unpack image "my-registry/my-registry/my-repository@sha256:292638896047d855da3c2f531ccecd0e172a06344840bebf5c2d7d59c36c2e08": failed to copy: httpReadSeeker: failed open: could not fetch content descriptor sha256:292638896047d855da3c2f531ccecd0e172a06344840bebf5c2d7d59c36c2e08 (application/octet-stream) from remote: not found`

**Comment by chengfang** [comment]
Please upgrade to the patch release 0.15.1, which contains *important* bug fixes. It may not fix this issue but will prevent future errors.

**Comment by chengfang** [comment]
Without this `backstage.image.registry` parameter in helm values, does everything work fine?

**Comment by leezhihui** [comment]
If has no backstage.image.registry, the argocd will deploy the app failed? before the argocd image updater work

**Comment by leezhihui** [comment]
removed backstage.image.repository and it works, so there has default ?

**Comment by MaksimKlepikov** [comment]
Although in [this](https://github.com/chengfang/image-updater-examples/blob/main/write-helmvalues/source2/values.yaml) and [this](https://github.com/chengfang/image-updater-examples/blob/main/helmvalues-list/source2/values.yaml) examples I see the use of the `registry` parameter.
Though proof-of-work with configured image-name, image-tag annotations are not presented in the commit history.
Are these examples correct and supposed to work?

**Comment by chengfang** [comment]
looks like helm always concatenate `registry` and `repository`, even when `repository` already starts with `registry`. You can verify this by running `helm template chart-name-xxx app/my-values.yaml` command in your application without argo-cd or running cluster.

I'll look into if image updater can use the shorter image name without registry in this case.

**Comment by chengfang** [comment]
With my sample in https://github.com/chengfang/image-updater-examples/blob/main/write-helmvalues/source2/values.yaml, after image updater run, the values file:
```yaml
image:
  registry: docker.io
  repository: docker.io/bitnamilegacy/nginx
  tag: 1.27.5
```

Running `helm template` produces the wrong image: `image: docker.io/docker.io/bitnamilegacy/nginx:1.27.5`
```
cd ~/go/src/image-updater-examples/write-helmvalues
helm repo add bitnami https://charts.bitnami.com/bitnami
helm pull bitnami/nginx --untar
helm template nginx --values source2/values.yaml
```

This need to be fixed, but also aware that some values files do not have `registry`, and some apps do need `repository` containing registry url.

update: with the fix in PR #1312 , runing image updater with the above sample app produces the correct changes to helm values file (registry url is not prepended to repository):

<img width="671" height="369" alt="Image" src="https://github.com/user-attachments/assets/110ba3b3-650e-4cf3-9df7-a8924859565b" />

**Comment by chengfang** [comment]
Fixed with above PR #1312  in `master-annotation-based` branch.

**Comment by MaksimKlepikov** [comment]
Thanks for the fix. 
But one edge case is still not supported.
When you have url path in the registry parameter the updater doesn't respect it.
E.g. original `values.yaml`:
```yaml
image:
  registry: my.private.registry/some-sub-path
  repository: feature-123
  tag: e54096ea
```
With application annotations:
```yaml
      annotations:
        "argocd-image-updater.argoproj.io/helm.image-name": image.repository
        "argocd-image-updater.argoproj.io/helm.image-tag": image.tag
```
And deployment using image parameters like this:
```yaml
      containers:
        - image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```

gets converted into:
```yaml
image:
  registry: my.private.registry/some-sub-path
  repository: some-sub-path/feature-123
  tag: new-tag-value
```

While I'm expecting:
```yaml
image:
  registry: my.private.registry/some-sub-path
  repository: feature-123
  tag: new-tag-value
```
